---
title: "Dataset Wrangling"
author: "Jonah Hamilton"
date: "2023-02-27"
output: html_document
---

## Data

The salary information dataset was extracted from [ai-jobs.net](https://ai-jobs.net/salaries/download/)

The geo-location dataset was extracted from the following [GitHub repo](https://gist.github.com/tadast/8827699)

```{r download-data, include=FALSE }
library(tidyverse)

salary_data <- read_csv('../data/salaries.csv')

map_data <- read_csv('../data/countries_codes_and_coordinates.csv')

```

## Data Wrangling

```{r}

merged_df <- merge(salary_data, map_data, 
                   by.x = "company_location",
                   by.y = "Alpha-2 code",
                   all.x = TRUE)

# fix column labels
merged_df <- merged_df |>
  rename(
    "latitude" = "Latitude (average)",
    "longitude" = "Longitude (average)",
    "alpha-3-code" = "Alpha-3 code",
    "numeric_code" = "Numeric code",
    "country" = "Country"
  )

# fix country names so polygons will display properly
merged_df <- merged_df |>
    mutate(country = str_replace(country, "Bolivia, Plurinational State of",
                                 "Bolivia")) |>
    mutate(country = str_replace(country, "Bahamas",
                                 "The Bahamas")) |>
    mutate(country = str_replace(country, "Iran, Islamic Republic of",
                                 "Iran")) |>
    mutate(country = str_replace(country, "Moldova, Republic of",
                                 "Moldova")) |>
    mutate(country = str_replace(country,"Macedonia, the former Yugoslav Republic of",
                                 "Macedonia")) |>
    mutate(country = str_replace(country, "Russian Federation",
                                 "Russia")) |>
    mutate(country = str_replace(country, "United States",
                                 "United States of America")) |>
    mutate(country = str_replace(country, "Viet Nam",
                                 "Vietnam"))

# save merged file in data directory
write.csv(merged_df, '../data/merged_salaries.csv')

# check we still have 70 unique countries
length(unique(merged_df$company_location))

# summarize the dataset
summary(merged_df)


```
